trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - main
  drafts: false
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

stages:
  - template: pipelines/templates/stages/ci.yml
