trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - main
  drafts: false
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  - group: Common
  - name: artifactName
    value: 'drop'
  # TODO Read the function app resource name as an output variable from the 'EES - Search - Infrastructure and Deploy' pipeline?
  - name: azureFunctionAppNameDev
    value: 's101d01-ees-fa-nlsearch'
  - name: azureFunctionAppNameTest
    value: 's101t01-ees-fa-nlsearch'
  - name: azureFunctionAppNamePreProd
    value: 's101p02-ees-fa-nlsearch'
  - name: azureFunctionAppNameProd
    value: 's101p01-ees-fa-nlsearch'
  - name: isDeployableBranch
    value: ${{and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))}}

stages:
  - template: pipelines/templates/stages/ci.yml
    parameters:
      artifactName: $(artifactName)

  - template: pipelines/templates/stages/deploy.yml
    parameters:
      artifactName: $(artifactName)
      condition: |
            and(
              succeeded(),
              eq(variables.isDeployableBranch, true)
            )
      dependsOn:
        - 'CI'
      environmentName: Dev
      functionAppName: $(azureFunctionAppNameDev)
      serviceConnection: $(serviceConnectionDev)
      stageName: 'Deploy_Dev'

  - template: pipelines/templates/stages/deploy.yml
    parameters:
      artifactName: $(artifactName)
      dependsOn:
        - 'Deploy_Dev'
      environmentName: Test
      functionAppName: $(azureFunctionAppNameTest)
      serviceConnection: $(serviceConnectionTest)
      stageName: 'Deploy_Test'

  - template: pipelines/templates/stages/deploy.yml
    parameters:
      artifactName: $(artifactName)
      dependsOn:
        - 'Deploy_Test'
      environmentName: Pre-Prod
      functionAppName: $(azureFunctionAppNamePreProd)
      serviceConnection: $(serviceConnectionPreProd)
      stageName: 'Deploy_PreProd'

  - template: pipelines/templates/stages/deploy.yml
    parameters:
      artifactName: $(artifactName)
      dependsOn:
        - 'Deploy_PreProd'
      environmentName: Prod
      functionAppName: $(azureFunctionAppNameProd)
      serviceConnection: $(serviceConnectionProd)
      stageName: 'Deploy_Prod'
