parameters:
  - name: artifactName
    type: string
    default: 'drop'

jobs:
  - job: PythonBuild
    displayName: 'Python build and test'
    steps:
      - checkout: self

      - template: ../steps/python/setup.yml

      - template: ../steps/python/test.yml

      - template: ../steps/python/publish.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
