parameters:
  - name: artifactName
    type: string
    default: 'drop'

stages:
  - stage: CI
    displayName: 'CI'

    jobs:
      - template: ../jobs/python-build.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
          publishBuild: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}