parameters:
  - name: artifactName
    type: string
    default: 'drop'
  - name: publishBuild
    type: boolean
    default: false

stages:
  - stage: CI
    displayName: 'CI'

    jobs:
      - template: ../jobs/python-build.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
          publishBuild: ${{ parameters.publishBuild }}
