stages:
  - stage: CI
    displayName: 'CI'

    jobs:
      - template: ../jobs/python-build.yml
        parameters:
          publishBuild: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}