parameters:
  - name: artifactName
    type: string
    default: 'drop'
  - name: condition
    type: string
    default: succeeded()
  - name: dependsOn
    type: object
    default: []
  - name: environmentName
    type: string
  - name: functionAppName
    type: string
  - name: serviceConnection
    type: string
  - name: stageName
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    displayName: 'Deploy to ${{ parameters.environmentName }}'
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}

    jobs:
      - template: ../jobs/deploy-function-app.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
          environmentName: ${{ parameters.environmentName }}
          functionAppName: ${{ parameters.functionAppName }}
          serviceConnection: ${{ parameters.serviceConnection }}
